import { trainers } from "#entities/Trainer";
import type { Training } from "./types";

export const trainings: Training[] = [
  {
    id: 1,
    title: "Групповая тренировка уровень D",
    trainer: trainers[0],
    station: "Сколково",
    time: "14:00",
    duration: "60 мин",
    freeSlots: 0,
    maxSlots: 2,
  },
  {
    id: 2,
    title: "Групповая тренировка уровень D+",
    trainer: trainers[1],
    station: "Сколково",
    time: "14:00",
    duration: "60 мин",
    freeSlots: 2,
    maxSlots: 2,
  },
  {
    id: 3,
    title: "Сплит C",
    trainer: trainers[2],
    station: "Селигерская",
    time: "14:00",
    duration: "60 мин",
    freeSlots: 0,
    maxSlots: 2,
  },
  {
    id: 4,
    title: "Групповая тренировка уровень D",
    trainer: trainers[3],
    station: "Нагатинская Премиум",
    time: "14:00",
    duration: "60 мин",
    freeSlots: 2,
    maxSlots: 2,
  },
  {
    id: 5,
    title: "Игра+Тренер. Уровень D",
    trainer: trainers[4],
    station: "Терехово",
    time: "14:00",
    duration: "60 мин",
    freeSlots: 0,
    maxSlots: 2,
  },
  {
    id: 6,
    title: "Групповая тренировка уровень D+",
    trainer: trainers[5],
    station: "Нагатинская",
    time: "14:00",
    duration: "60 мин",
    freeSlots: 0,
    maxSlots: 2,
  },
  {
    id: 7,
    title: "Групповая тренировка уровень C/C+",
    trainer: trainers[6],
    station: "Сколково",
    time: "15:00",
    duration: "60 мин",
    freeSlots: 2,
    maxSlots: 2,
  },
  {
    id: 8,
    title: "Игра+Тренер. Уровень D+",
    trainer: trainers[0],
    station: "Сколково",
    time: "15:00",
    duration: "60 мин",
    freeSlots: 0,
    maxSlots: 2,
  },
  {
    id: 9,
    title: "Сплит D+",
    trainer: trainers[2],
    station: "Селигерская",
    time: "15:00",
    duration: "60 мин",
    freeSlots: 0,
    maxSlots: 2,
  },
  {
    id: 10,
    title: "Игра+Тренер. Уровень C",
    trainer: trainers[3],
    station: "Нагатинская Премиум",
    time: "15:00",
    duration: "60 мин",
    freeSlots: 0,
    maxSlots: 2,
  },
];
